global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'nodes'
    static_configs:
    - targets: ['192.168.10.15:9100', '192.168.10.20:9102']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'rabbit'
    static_configs:
      - targets: ['192.168.10.18:15692']
